### ISSUE TITLE
DeprecationWarning from typescript 4.8.4

### ISSUE THREAD

**Issue by nakagawa424** [wessberg/ts-clone-node#8]
DeprecationWarning: 'isTypeAssertion' has been deprecated since v4.0.0. Use `isTypeAssertionExpression` instead.
DeprecationWarning: 'updateImportTypeNode' has been deprecated since v4.6.0. Use the overload that accepts 'assertions'
DeprecationWarning: 'createTypeParameterDeclaration' has been deprecated since v4.7.0. Use the overload that accepts 'modifiers'
DeprecationWarning: 'createImportTypeNode' has been deprecated since v4.6.0. Use the overload that accepts 'assertions'

**Comment by artola** [comment]
At least for the first warning: `DeprecationWarning: 'isTypeAssertion' has been deprecated since v4.0.0. Use isTypeAssertionExpression instead.`

From my point of view, the error is generated here:

https://github.com/wessberg/ts-clone-node/blob/7ddb943770284b7111e4c2047f6e1e31fdf4cb10/src/clone-node/clone-node.ts#L549

The code asserts existence of `isTypeAssertionExpression` but if the function returns false, still try to use `isTypeAssertion`. It can be fixed with a ternary:

```javascript
    else if (
      "isTypeAssertionExpression" in options.typescript 
        ? options.typescript.isTypeAssertionExpression(node)
        : ("isTypeAssertion" in options.typescript && options.typescript.isTypeAssertion(node)
     ) {
        return cloneTypeAssertion(node, options);
    }
```

@wessberg Could you please fix it? I found this warning because of the use of this dependency in `rollup-plugin-ts`.

**Comment by marcj** [comment]
It's not only these deprecated warnings, but TS 4.8 introduced big API breaking changes in the node factory, so it's more work than that. I've fixed these in my fork `@marcj/ts-node-clone` if anyone wants a fix right now.

**Comment by nakagawa424** [comment]
rollup-plugin-ts@3.1.1 (ts-clone-node@2.0.4) works fine for me.

thanx

**Comment by justinfagnani** [comment]
@marcj do you have your changes published anywhere? Are you going to upstream them?

**Comment by marcj** [comment]
@justinfagnani its a public repo

**Comment by justinfagnani** [comment]
@marcj if this is it: https://github.com/marcj/ts-clone-node I don't see any commits from you and one one branch. It looks like it's just a few commits behind upstream.

**Comment by marcj** [comment]
@justinfagnani Oh, I had it only on NPM. I pushed the changes to the repo now

**Comment by wessberg** [comment]
@justinfagnani this issue was introduced before I went in and added TS 4.9 support to `ts-clone-node`.
The latest version is compatible with the latest Compiler API changes and does not produce deprecation warnings when used with TS4.9

Can you verify that you're actually using the latest versions of `ts-clone-node` (v2.0.4), and if by any chance you're using it transitively through `rollup-plugin-ts`, that you're using the latest version of that? (v.3.2.0)
